### ISSUE TITLE
Migrate 2017 & 2018 Public Schools data packages & datasets to follow 2019 schema

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#626]
Currently public schools data packages organize `sca_bluebook` and `doe_lcgms` datasets as two distinct tables.  For the 2019 data update, EDM is combining them into one dataset, which better represent the information (`doe_lcgms` is really an extension of `sca_bluebook` to add more detail/schools that aren't in bluebook, but they follow the same schema).

The `public_schools` [data packages](https://github.com/NYCPlanning/ceqr-app/blob/dff54d9ed2a286d051499e4179ecaca885887e67/backend/db/seeds.rb#L1) need to follow the same schema for all years (2017, 2018, and 2019) - otherwise we will have to add conditional logic on the backend and frontend to allow for a user who is switching between data packages within the public schools analysis to accomodate this difference between data package schemas.

As it is now, lcgms and bluebooks schools are being merged in the [frontend model](https://github.com/NYCPlanning/ceqr-app/blob/dff54d9ed2a286d051499e4179ecaca885887e67/frontend/app/models/public-schools-analysis.js#L92).  By addressing this upstream in the backend data model, we can refactor to simplify the Ember public schools analysis model.

For this issue, we need to:
- [x] Manually combine previous `bluebook` and `lcgms` datasets in `ceqr_data` database to align with new schema.  `doe_lcgms.2017` an d`sca_bluebook.2017` should become `ceqr_school_buildings.2017`, and same for the 2018 tables. #628 
- [ ] Update the rails data packages. 
  - [x] modify `seeds.db` #631 
  - [ ] run `rails db:seed`
  - [ ] *Need to ensure that existing project successfully migrate to this new schema.*
- [ ] Trace where this impacts backend or frontend application logic and update with the expectation of the new ceqr_school_buildings #629 
- [ ] Refactor frontend public schools analysis model #630 

Related to #484

**Comment by trbmcginnis** [comment]
Closing this because it'll be covered in #630
