### ISSUE TITLE
Data: ACS Update

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/ceqr-app#627]
Our goal is to create a new data package representing the 2018 version of ACS 5-year data, i.e. a data package pointing to a new `nyc_acs.2018` table.

CEQR already has a data package for "ACS 5-year 2017", which points to the nyc_acs.2017 table. Meanwhile ACS 2018 is already released at data.census.gov.

For this year's ACS update, Labs will also have to figure out the data processing to transform and load raw ACS data into the `nyc_acs.2018` and `nyc_census_tracts.[????]` tables. In the future EDM will work to take ownership of this step, ideally in the form of a consolidated ACS pipeline for all apps.

**Remaining questions**
- [ ] Is there a new `nyc_census_tracts` dataset with updated census tract boundaries that should correspond to 2017 ACS data?  
- [x] Where and how is the source ACS data acquired?
  - Specifically for source data in this old repo: https://github.com/NYCPlanning/db-ceqr-acs/tree/master/2017/sources
   - **Answer:** The source data in the repo is acquired from American Fact Finder (AFF). However, AFF will be taken offline on March 31, and doesn't provide 2018 data. This means we won't be able to 2018 data in the same format as previously. We'll have to download it in the new format and rework the python processing scripts.
  - For 2018: 
    - Use the REST API, as EDM is doing. This will come back as JSON.
- [x] How does the 2017 data processing script Jonathan wrote transform source data to nyc_acs?   I.e. What real-world concept does nyc_acs represent?
    - **Answer:** It takes the Population and Means of Transportation census datasets, flattens/denormalizes the datasets (creating a row for each geoid - variable pair), then combines the two datasets. 

**Tasks summary:**

1. Download 2018 ACS 5-year data, with filters matching those applied through American Fact Finder for 2017 data.
  - Filters:
    - Topic: Means of Transportation (id B08301*)
    - Time range: 5-year (2014-2018)
    - Geography: Census Tract Level (140) within NYC counties (Richmond, New York, Kings, Queens, Bronx) 
2. ~If data wasn't downloaded with filters applied, post-process the data to filter it.~
3. Write python script to..
  a. transform fetched data to CEQR schema. Reference EDM's `db-acs` pipeline scripts and `db-acs-ceqr/ACS-merge.py` to write this. 
  b. Export to CSV.
  c. Load CSV to target database
**Note:** Jupyter Notebooks was used to write the script. It provided an environment with necessary packages installed. However, to run the script locally and avoid relying on something like virtualenv, we should set up python environment on Docker. 
5. Run scripts to load data into `nyc_acs.2018 table` develop, staging and production database
6. Modify seed seed file and create data package for `nyc_acs.2018` in development, staging and production databases.
7. Verify frontend functionality

**Comment by allthesignals** [comment]
Who's picking this up? We assigned it for this sprint so wanna make sure someone tackles it. @bfreeds?

**Comment by allthesignals** [comment]
This is on staging but we are blocked promoting develop into master because of conflicts (messy git history)

**Comment by allthesignals** [comment]
Holding off on promoting ^
